fixed empty/no script tag in vue component error
trivago/prettier-plugin-sort-imports pull request #192
Opened 2022-11-29 01:20 UTC by adamDilger

This should fix https://github.com/trivago/prettier-plugin-sort-imports/issues/191 if I've understood what `vue-preprocessor.ts` does

If there is no script value, just return the code as is

2022-12-09 20:22 UTC, HunterLarco approved these changes

2022-12-13 13:30 UTC, byara requested changes
Thank you for your contribution. Could you please use this example and also some variation of it in the snapshot tests? 

```
<template>
	<div>
		<span>hello world
		</span></div>
</template>

<script>
// I am top level comment in this file.
// I am second line of top level comment in this file.
import threeLevelRelativePath from '../../../threeLevelRelativePath';
import sameLevelRelativePath from './sameLevelRelativePath';
import thirdParty from 'third-party';
import React from 'react';
export { random } from './random';
import oneLevelRelativePath from '../oneLevelRelativePath';
import otherthing from '@core/otherthing';
import twoLevelRelativePath from '../../twoLevelRelativePath';
import component from '@ui/hello';
export default {
    title: 'hello',
};
import fourLevelRelativePath from '../../../../fourLevelRelativePath';
import something from '@server/something';
function add(a, b) {
    return a + b;
}
</script>

<style>
div { color: red; }
</style>
```
These kinds of tests help us to catch unwanted changes through out the code.
Thank 👍

2022-12-13 22:13 UTC, adamDilger commented
@byara From the looks it seems that there are already a few examples/variations of a standard component in the snapshots, so instead I've added the bug offending scenario (a component with no script tag). Is that all good?

Thanks!

2022-12-14 14:20 UTC, byara approved these changes
Thank you for the changes 👍

2022-12-14 14:21 UTC, ayusharma approved these changes

2022-12-14 14:21 UTC, merged

2023-02-23 15:47 UTC, ayusharma commented
Released in [v4.1.0](https://github.com/trivago/prettier-plugin-sort-imports/releases/tag/v4.1.0). I appreciate your patience. ❤️