[Feature] Add <SEPARATOR> special word
trivago/prettier-plugin-sort-imports pull request #296
Opened 2024-06-01 07:44 UTC by joutvhu

Implement feature https://github.com/trivago/prettier-plugin-sort-imports/issues/268

2024-06-01 07:49 UTC, joutvhu commented
Hi @ayusharma, @byara
Please help to review

2024-12-06 02:04 UTC, forivall commented
This will need [my additional changes (joutvhu/prettier-plugin-sort-imports#2)](https://github.com/joutvhu/prettier-plugin-sort-imports/pull/2) before merging, as adding tests revealed some critical issues.

2024-12-08 15:02 UTC, byara commented
Hey @joutvhu can we please update this PR with some tests mentioned by @forivall?

2024-12-09 10:49 UTC, byara commented
I changes the base branch to v6. Let's release it there.

2024-12-09 17:30 UTC, joutvhu commented
@byara I added tests

2024-12-12 16:25 UTC, forivall commented on tests/Separator/imports-with-comments.ts
this doesnt have any comments? I already included tests in `ImportsManualSeparated`, so i think these `Separator` tests can be removed.

2025-01-02 13:33 UTC, byara requested changes
Thank you for the PR 👏 really appreciate the effort you have put into this!
I left a comment, could you please take a look?

2025-01-02 13:33 UTC, byara commented on tests/Separator/imports-with-comments.ts
Hey @joutvhu can you please address this comment?
There might be some other tests within a copy of this PR from [here](https://github.com/trivago/prettier-plugin-sort-imports/pull/339), it would be nice to add those too.

2025-09-08 23:24 UTC, forivall commented
This pr is now obsolete with https://github.com/trivago/prettier-plugin-sort-imports/pull/339 merged now, so i think this can be safely closed.

2025-09-09 08:08 UTC, closed without merging