[#34] add support for shebang
trivago/prettier-plugin-sort-imports pull request #43
Opened 2021-03-28 09:05 UTC by byara

Closes #34

2021-03-28 14:24 UTC, ayusharma requested changes
Small improvements

2021-03-28 14:24 UTC, ayusharma commented on src/utils/get-code-from-ast.ts
> +    interpreter: InterpreterDirective | null | undefined,
```suggestion
    interpreter?: InterpreterDirective
```
May be undefined or ImperativeDirective

2021-03-28 14:24 UTC, ayusharma commented on src/utils/get-code-from-ast.ts
> +        interpreter: interpreter ? interpreter : null,
Can we make interpreter undefined?

2021-03-29 07:27 UTC, byara commented on src/utils/get-code-from-ast.ts
> +        interpreter: interpreter ? interpreter : null,
Yes. The type definition is:
```typescript
interface Program extends BaseNode {
    type: "Program";
    body: Array<Statement>;
    directives: Array<Directive>;
    sourceType: "script" | "module";
    interpreter?: InterpreterDirective | null;
    sourceFile: string;
}
```

2021-03-30 13:12 UTC, ayusharma approved these changes

2021-03-30 13:13 UTC, merged